In [ ]:
import pandas as pd

df = pd.read_csv('/content/student_startup_success_dataset 2.csv')

df.head()

,project_id,institution_name,institution_type,project_domain,team_size,avg_team_experience,innovation_score,funding_amount_usd,mentorship_support,incubation_support,market_readiness_level,competition_awards,business_model_score,technology_maturity,year,success_label
0,P0001,Institution_39,Non-technical,AgriTech,3,1.35,0.75,48336.75,1,1,3,3,0.86,4,2023,1
1,P0002,Institution_29,Technical,FinTech,4,1.57,0.38,30601.34,0,0,5,0,0.39,5,2023,0
2,P0003,Institution_15,Non-technical,AgriTech,3,2.19,0.61,37712.58,1,1,1,0,0.38,2,2019,1
3,P0004,Institution_8,Private,GreenTech,7,0.72,0.98,46881.00,1,1,5,1,0.69,5,2021,1
4,P0005,Institution_21,Public,HealthTech,7,2.64,0.33,29988.37,0,0,4,2,0.85,2,2020,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   project_id              2100 non-null   object
 1   institution_name        2100 non-null   object
 2   institution_type        2100 non-null   object
 3   project_domain          2100 non-null   object
 4   team_size               2100 non-null   int64
 5   avg_team_experience     2100 non-null   float64
 6   innovation_score        2100 non-null   float64
 7   funding_amount_usd      2100 non-null   float64
 8   mentorship_support      2100 non-null   int64
 9   incubation_support      2100 non-null   int64
 10  market_readiness_level  2100 non-null   int64
 11  competition_awards      2100 non-null   int64
 12  business_model_score    2100 non-null   float64
 13  technology_maturity     2100 non-null   int64
 14  year                    2100 non-null   int64
 15  success_label           2100 non-null   int64
dtypes: float64(4), int64(8), object(4)
memory usage: 262.6+ KB

In [ ]:
df['success_label'].value_counts()

success_label
0    1219
1     881
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop(columns=['project_id', 'institution_name'])

In [ ]:
df = pd.get_dummies(
    df,
    columns=['institution_type', 'project_domain'],
    dtype=int
)

In [ ]:
df.head()

,team_size,avg_team_experience,innovation_score,funding_amount_usd,mentorship_support,incubation_support,market_readiness_level,competition_awards,business_model_score,technology_maturity,...,success_label,institution_type_Non-technical,institution_type_Private,institution_type_Public,institution_type_Technical,project_domain_AgriTech,project_domain_EdTech,project_domain_FinTech,project_domain_GreenTech,project_domain_HealthTech
0,3,1.35,0.75,48336.75,1,1,3,3,0.86,4,...,1,1,0,0,0,1,0,0,0,0
1,4,1.57,0.38,30601.34,0,0,5,0,0.39,5,...,0,0,0,0,1,0,0,1,0,0
2,3,2.19,0.61,37712.58,1,1,1,0,0.38,2,...,1,1,0,0,0,1,0,0,0,0
3,7,0.72,0.98,46881.00,1,1,5,1,0.69,5,...,1,0,1,0,0,0,0,0,1,0
4,7,2.64,0.33,29988.37,0,0,4,2,0.85,2,...,0,0,0,1,0,0,0,0,0,1

In [ ]:
X = df.drop(columns=['success_label'])
y = df['success_label']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(1680, 20)
(420, 20)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9952380952380953